POST https://node-do-zero-wl64.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}
###

GET https://node-do-zero-wl64.onrender.com/videos

###

PUT https://node-do-zero-wl64.onrender.com/videos/a00f86b5-4098-435c-903c-0c2e5e0d3880
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o segundo video",
    "duration": 190
}

###

DELETE https://node-do-zero-wl64.onrender.com/videos/a00f86b5-4098-435c-903c-0c2e5e0d3880